#pragma warning disable CS1591
using System.Collections.ObjectModel;
using System.Globalization;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using Greenflux.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Greenflux.ChargeAssist;

public interface IChargeAssistClient
    {

        Task<AccountInfo> Account_MapUserAndDriversAsync(MapUserAndDriversRequest? body = null, CancellationToken cancellationToken = default);

        Task<TokenModelListResponse> AppToken_RegisterAsync(string appToken, CancellationToken cancellationToken = default);

        Task<TokenModelListResponse> AppToken_RegisterWithDriverAsync(CreateUpdateAppTokenWithDriverRequest? body = null, CancellationToken cancellationToken = default);

        Task<SessionHistoryModelListResponse> AppToken_GetSessionsAsync(string appToken, string? filter_paymentMethodIds = null, DateTimeOffset? filter_dateTimeFrom = null, DateTimeOffset? filter_dateTimeTo = null, string? filter_chargeSessionId = null, string? filter_ocpiSessionId = null, ChargeAssistPaymentMethodType? filter_paymentMethodType = null, IEnumerable<ChargeAssistSessionStatus>? filter_sessionStatus = null, bool? sortDesc = null, CancellationToken cancellationToken = default);

        Task<SessionHistoryV2ModelListResponse> AppTokenV2_GetSessionsAsync(string appToken, string? filter_paymentMethodIds = null, DateTimeOffset? filter_dateTimeFrom = null, DateTimeOffset? filter_dateTimeTo = null, string? filter_chargeSessionId = null, string? filter_ocpiSessionId = null, ChargeAssistPaymentMethodType? filter_paymentMethodType = null, IEnumerable<ChargeAssistSessionStatus>? filter_sessionStatus = null, string? continuationToken = null, bool? sortDesc = null, CancellationToken cancellationToken = default);

        Task<TokenModel> AppTokenV2_GetAsync(string appToken, CancellationToken cancellationToken = default);

        /// <summary>Returns the token model, or <c>null</c> when the token is not found (HTTP 404).</summary>
        Task<TokenModel?> AppTokenV2_TryGetAsync(string appToken, CancellationToken cancellationToken = default);

        Task<TokenModel> AppTokenV2_CreateAsync(CreateAppTokenRequest? body = null, CancellationToken cancellationToken = default);

        Task<LocationSummaryGeoListResponse> Favorites_GetLocationsAsync(string appToken, double? userLatitude = null, double? userLongitude = null, CancellationToken cancellationToken = default);

        Task Favorites_AddLocationAsync(string appToken, string id, FavoriteRequest? body = null, CancellationToken cancellationToken = default);

        Task Favorites_RemoveLocationAsync(string appToken, string id, CancellationToken cancellationToken = default);

        Task<LocationSummaryGeoListResponse> FavoritesV2_GetLocationsAsync(string appToken, string? filter_evseUid = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, CancellationToken cancellationToken = default);

        Task FavoritesV2_AddLocationAsync(string appToken, string id, FavoriteRequest? body = null, CancellationToken cancellationToken = default);

        Task FavoritesV2_RemoveLocationAsync(string appToken, string id, CancellationToken cancellationToken = default);

        Task<LocationRatingV2Model> LocationRating_CreateAsync(LocationRatingV2Request? body = null, CancellationToken cancellationToken = default);

        Task<ICollection<LocationRatingOptionV2Model>> LocationRating_GetOptionsAsync(CancellationToken cancellationToken = default);

        Task<LocationSummaryGeoListResponse> Locations_SearchAsync(string q, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, string? paymentMethodId = null, CancellationToken cancellationToken = default);

        Task<LocationSummaryGeoListResponse> Locations_GetNearbyAsync(double latitude, double longitude, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, string? paymentMethodId = null, CancellationToken cancellationToken = default);

        Task<LocationSummaryGeoListResponse> Locations_GetBoundingBoxAsync(double bottomLeftLat, double bottomLeftLng, double topRightLat, double topRightLng, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, string? paymentMethodId = null, CancellationToken cancellationToken = default);

        Task<LocationMinModelGeoListResponse> Locations_GetBoundingBoxMinimalAsync(double? bottomLeftLat = null, double? bottomLeftLng = null, double? topRightLat = null, double? topRightLng = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<LocationPoiResultListResponse> Locations_GetBoundingBoxTileAsync(int? x = null, int? y = null, int? zoomLevel = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, int? overlapPixel = null, CancellationToken cancellationToken = default);

        Task<LocationModel> Locations_GetByIdAsync(string id, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, string? paymentMethodId = null, CancellationToken cancellationToken = default);

        Task<LocationModel> Locations_GetByEvseAsync(string evseUid, string? filter_appToken = null, CancellationToken cancellationToken = default);

        Task<LocationSummaryGeoListResponse> Locations_GetAllAsync(string? filter_appToken = null, string? filter_country = null, IEnumerable<string>? filter_locationIds = null, DateTimeOffset? filter_lastUpdated = null, bool? filter_restrictedAccess = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<LocationAvailabilityResponse> Locations_GetAvailabilityAsync(LocationAvailabilityRequest? body = null, CancellationToken cancellationToken = default);

        Task<LocationModelGeoListResponse> LocationsV2_SearchAsync(string? q = null, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, string? paymentMethodId = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<LocationModelGeoListResponse> LocationsV2_GetNearbyAsync(double? latitude = null, double? longitude = null, string? paymentMethodId = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, int? pageSize = null, CancellationToken cancellationToken = default);

        Task<LocationModelGeoListResponse> LocationsV2_GetBoundingBoxAsync(double? bottomLeftLat = null, double? bottomLeftLng = null, double? topRightLat = null, double? topRightLng = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, string? paymentMethodId = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<LocationMinModelGeoListResponse> LocationsV2_GetBoundingBoxMinimalAsync(double? bottomLeftLat = null, double? bottomLeftLng = null, double? topRightLat = null, double? topRightLng = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<LocationModel> LocationsV2_GetByIdAsync(string id, string? paymentMethodId = null, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, CancellationToken cancellationToken = default);

        Task<LocationModel> LocationsV2_GetByEvseAsync(string evseUid, string? filter_appToken = null, CancellationToken cancellationToken = default);

        Task<PaymentMethodModelListResponse> Payment_GetWalletAsync(string appToken, string? locationId = null, CancellationToken cancellationToken = default);

        /// <summary>Returns the wallet, or <c>null</c> when the token is not found (HTTP 404).</summary>
        Task<PaymentMethodModelListResponse?> Payment_TryGetWalletAsync(string appToken, string? locationId = null, CancellationToken cancellationToken = default);

        Task<PaymentMethodModel> Payment_AddExternalMethodAsync(string appToken, PutExternalPaymentMethodRequest? body = null, CancellationToken cancellationToken = default);

        Task<PaymentMethodModel> Payment_AddChargeCardAsync(string appToken, PutChargeCardRequest? body = null, CancellationToken cancellationToken = default);

        Task<PaymentMethodModel> Payment_LinkChargeCardAsync(string appToken, LinkChargeCardRequest? body = null, CancellationToken cancellationToken = default);

        Task<PaymentMethodModel> Payment_UnlinkChargeCardAsync(string appToken, UnLinkChargeCardRequest? body = null, CancellationToken cancellationToken = default);

        Task<PaymentMethodModel> Payment_AddPspMethodAsync(string appToken, PspSource pspSource, PutPspTokenRequest? body = null, CancellationToken cancellationToken = default);

        Task Payment_DeleteMethodAsync(string appToken, string id, CancellationToken cancellationToken = default);

        Task<LocationModelListResponse> PrivateLocations_GetAsync(string appToken, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<QrResponse> Qr_ParseAsync(QrRequest? body = null, CancellationToken cancellationToken = default);

        Task ServiceStatus_GetAsync(CancellationToken cancellationToken = default);

        Task<StartResponse> Session_StartAsync(string appToken, StartRequest? body = null, CancellationToken cancellationToken = default);

        Task<StatusResponse> Session_StopAsync(string appToken, StopRequest? body = null, CancellationToken cancellationToken = default);

        Task Session_UpdateMileageAsync(string appToken, SessionMileageRequest? body = null, CancellationToken cancellationToken = default);

        Task<StatusResponse> Session_GetStatusAsync(string appToken, string chargeSessionId, int? maxDataPoints = null, CancellationToken cancellationToken = default);

        Task<HighPriorityResponse> Session_SetHighPriorityAsync(string? appToken = null, HighPriorityRequest? body = null, CancellationToken cancellationToken = default);

        Task<ExternalCdrInformationModel> Session_GetExternalCdrAsync(string cdrId, string authId, CancellationToken cancellationToken = default);

        Task<IActionResult> SessionFailedPayments_InitiateAsync(RetryFailedSessionPaymentRequest? body = null, CancellationToken cancellationToken = default);

        Task<FailedSessionPaymentModelListResponse> SessionFailedPayments_GetAsync(string appToken, string? paymentMethodId = null, string? continuationToken = null, CancellationToken cancellationToken = default);

        Task<SessionRatingV2Model> SessionRating_CreateAsync(SessionRatingAllV2Request? body = null, CancellationToken cancellationToken = default);

        Task<SessionRatingV2Model> SessionRating_SetRatingAsync(SessionRatingV2Request? body = null, CancellationToken cancellationToken = default);

        Task<SessionRatingV2Model> SessionRating_SetFeedbackAsync(SessionRatingFeedbackV2Request? body = null, CancellationToken cancellationToken = default);

        Task<SessionRatingV2Model> SessionRating_GetAsync(string chargeSessionId, CancellationToken cancellationToken = default);

        Task<ICollection<RatingOptionV2Model>> SessionRating_GetOptionsAsync(CancellationToken cancellationToken = default);

        Task<StartResponse> SessionV2_StartAsync(string appToken, StartRequest? body = null, CancellationToken cancellationToken = default);

        Task<StatusResponse> SessionV2_StopAsync(string appToken, StopRequest? body = null, CancellationToken cancellationToken = default);

        Task SessionV2_UpdateMileageAsync(string appToken, SessionMileageRequest? body = null, CancellationToken cancellationToken = default);

        Task<StatusResponse> SessionV2_GetStatusAsync(string appToken, string chargeSessionId, int? maxDataPoints = null, CancellationToken cancellationToken = default);

        Task<HighPriorityResponse> SessionV2_SetHighPriorityAsync(string? appToken = null, HighPriorityRequest? body = null, CancellationToken cancellationToken = default);

        Task<WalletTariffItemListResponse> Tariff_GetAsync(string appToken, string locationId, string evseUid, string? connectorId = null, CancellationToken cancellationToken = default);

        Task<WalletTariffItem> Tariff_GetDefaultAsync(string locationId, string evseUid, string? connectorId = null, CancellationToken cancellationToken = default);

        Task<BulkTariffResponse> Tariff_GetBulkAsync(string appToken, string paymentMethodId, BulkTariffsRequest? body = null, CancellationToken cancellationToken = default);

        Task<VidMappingModel> Vid_RegisterAsync(string appToken, VidMappingRegisterRequestExternal? body = null, CancellationToken cancellationToken = default);

        Task<VidMappingModel> Vid_DeregisterAsync(string appToken, CancellationToken cancellationToken = default);

        Task<VidMappingModel> Vid_ChangePaymentMethodAsync(string appToken, VidChangePaymentMethodRequest? body = null, CancellationToken cancellationToken = default);

        Task Webhooks_ReceivePaymentStatusAsync(PaymentStatusRequest? body = null, CancellationToken cancellationToken = default);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
// ── Exception types ────────────────────────────────────────────────

public class ChargeAssistApiException : GreenfluxApiException
{
    public ChargeAssistApiException(string message, int statusCode, string? response,
        IReadOnlyDictionary<string, IEnumerable<string>> headers, Exception? innerException)
        : base(message, statusCode, response, headers, innerException) { }
}

public class ChargeAssistApiException<TResult> : ChargeAssistApiException
{
    public TResult Result { get; }

    public ChargeAssistApiException(string message, int statusCode, string? response,
        IReadOnlyDictionary<string, IEnumerable<string>> headers, TResult result, Exception? innerException)
        : base(message, statusCode, response, headers, innerException)
    {
        Result = result;
    }
}

// ── Client implementation ──────────────────────────────────────────

public class ChargeAssistClient : GreenfluxApiClient, IChargeAssistClient
{
    public ChargeAssistClient(HttpClient httpClient) : base(httpClient) { }

    public async Task<AccountInfo> Account_MapUserAndDriversAsync(MapUserAndDriversRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<AccountInfo>("account/mapuseranddrivers", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<TokenModelListResponse> AppToken_RegisterAsync(string appToken, CancellationToken cancellationToken = default) => await SendPutAsync<TokenModelListResponse>($"token/{Uri.EscapeDataString(appToken)}", null, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<TokenModelListResponse> AppToken_RegisterWithDriverAsync(CreateUpdateAppTokenWithDriverRequest? body = null, CancellationToken cancellationToken = default) => await SendPutAsync<TokenModelListResponse>("token", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<SessionHistoryModelListResponse> AppToken_GetSessionsAsync(string appToken, string? filter_paymentMethodIds = null, DateTimeOffset? filter_dateTimeFrom = null, DateTimeOffset? filter_dateTimeTo = null, string? filter_chargeSessionId = null, string? filter_ocpiSessionId = null, ChargeAssistPaymentMethodType? filter_paymentMethodType = null, IEnumerable<ChargeAssistSessionStatus>? filter_sessionStatus = null, bool? sortDesc = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_paymentMethodIds", filter_paymentMethodIds); AddParameter(p, "filter_dateTimeFrom", filter_dateTimeFrom); AddParameter(p, "filter_dateTimeTo", filter_dateTimeTo); AddParameter(p, "filter_chargeSessionId", filter_chargeSessionId); AddParameter(p, "filter_ocpiSessionId", filter_ocpiSessionId); AddParameter(p, "filter_paymentMethodType", filter_paymentMethodType); AddEnumerableParameter(p, "filter_sessionStatus", filter_sessionStatus?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "sortDesc", sortDesc); return await SendGetAsync<SessionHistoryModelListResponse>($"token/{Uri.EscapeDataString(appToken)}/sessions", p, cancellationToken).ConfigureAwait(false); }
    public async Task<SessionHistoryV2ModelListResponse> AppTokenV2_GetSessionsAsync(string appToken, string? filter_paymentMethodIds = null, DateTimeOffset? filter_dateTimeFrom = null, DateTimeOffset? filter_dateTimeTo = null, string? filter_chargeSessionId = null, string? filter_ocpiSessionId = null, ChargeAssistPaymentMethodType? filter_paymentMethodType = null, IEnumerable<ChargeAssistSessionStatus>? filter_sessionStatus = null, string? continuationToken = null, bool? sortDesc = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_paymentMethodIds", filter_paymentMethodIds); AddParameter(p, "filter_dateTimeFrom", filter_dateTimeFrom); AddParameter(p, "filter_dateTimeTo", filter_dateTimeTo); AddParameter(p, "filter_chargeSessionId", filter_chargeSessionId); AddParameter(p, "filter_ocpiSessionId", filter_ocpiSessionId); AddParameter(p, "filter_paymentMethodType", filter_paymentMethodType); AddEnumerableParameter(p, "filter_sessionStatus", filter_sessionStatus?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "continuationToken", continuationToken); AddParameter(p, "sortDesc", sortDesc); return await SendGetAsync<SessionHistoryV2ModelListResponse>($"v2.1/token/{Uri.EscapeDataString(appToken)}/sessions", p, cancellationToken).ConfigureAwait(false); }
    public async Task<TokenModel> AppTokenV2_GetAsync(string appToken, CancellationToken cancellationToken = default) => await SendGetAsync<TokenModel>($"v2.1/token/{Uri.EscapeDataString(appToken)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<TokenModel?> AppTokenV2_TryGetAsync(string appToken, CancellationToken cancellationToken = default) => await TrySendGetAsync<TokenModel>($"v2.1/token/{Uri.EscapeDataString(appToken)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<TokenModel> AppTokenV2_CreateAsync(CreateAppTokenRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<TokenModel>("v2.1/token", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<LocationSummaryGeoListResponse> Favorites_GetLocationsAsync(string appToken, double? userLatitude = null, double? userLongitude = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); return await SendGetAsync<LocationSummaryGeoListResponse>($"favorites/{Uri.EscapeDataString(appToken)}/locations", p, cancellationToken).ConfigureAwait(false); }
    public async Task Favorites_AddLocationAsync(string appToken, string id, FavoriteRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync($"favorites/{Uri.EscapeDataString(appToken)}/location/{Uri.EscapeDataString(id)}", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task Favorites_RemoveLocationAsync(string appToken, string id, CancellationToken cancellationToken = default) => await SendDeleteAsync($"favorites/{Uri.EscapeDataString(appToken)}/location/{Uri.EscapeDataString(id)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<LocationSummaryGeoListResponse> FavoritesV2_GetLocationsAsync(string appToken, string? filter_evseUid = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_evseUid", filter_evseUid); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); return await SendGetAsync<LocationSummaryGeoListResponse>($"v2.1/favorites/{Uri.EscapeDataString(appToken)}/locations", p, cancellationToken).ConfigureAwait(false); }
    public async Task FavoritesV2_AddLocationAsync(string appToken, string id, FavoriteRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync($"v2.1/favorites/{Uri.EscapeDataString(appToken)}/location/{Uri.EscapeDataString(id)}", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task FavoritesV2_RemoveLocationAsync(string appToken, string id, CancellationToken cancellationToken = default) => await SendDeleteAsync($"v2.1/favorites/{Uri.EscapeDataString(appToken)}/location/{Uri.EscapeDataString(id)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<LocationRatingV2Model> LocationRating_CreateAsync(LocationRatingV2Request? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<LocationRatingV2Model>("locationrating", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<ICollection<LocationRatingOptionV2Model>> LocationRating_GetOptionsAsync(CancellationToken cancellationToken = default) => await SendGetAsync<ICollection<LocationRatingOptionV2Model>>("locationrating/ratingoptions", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<LocationSummaryGeoListResponse> Locations_SearchAsync(string q, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, string? paymentMethodId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["q"] = q }; AddParameter(p, "filter_evseUid", filter_evseUid); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); AddParameter(p, "paymentMethodId", paymentMethodId); return await SendGetAsync<LocationSummaryGeoListResponse>("locations/search", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationSummaryGeoListResponse> Locations_GetNearbyAsync(double latitude, double longitude, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, string? paymentMethodId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["latitude"] = ConvertToString(latitude, CultureInfo.InvariantCulture), ["longitude"] = ConvertToString(longitude, CultureInfo.InvariantCulture) }; AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "paymentMethodId", paymentMethodId); return await SendGetAsync<LocationSummaryGeoListResponse>("locations/nearby", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationSummaryGeoListResponse> Locations_GetBoundingBoxAsync(double bottomLeftLat, double bottomLeftLng, double topRightLat, double topRightLng, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, string? paymentMethodId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["bottomLeftLat"] = ConvertToString(bottomLeftLat, CultureInfo.InvariantCulture), ["bottomLeftLng"] = ConvertToString(bottomLeftLng, CultureInfo.InvariantCulture), ["topRightLat"] = ConvertToString(topRightLat, CultureInfo.InvariantCulture), ["topRightLng"] = ConvertToString(topRightLng, CultureInfo.InvariantCulture) }; AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); AddParameter(p, "paymentMethodId", paymentMethodId); return await SendGetAsync<LocationSummaryGeoListResponse>("locations/boundingbox", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationMinModelGeoListResponse> Locations_GetBoundingBoxMinimalAsync(double? bottomLeftLat = null, double? bottomLeftLng = null, double? topRightLat = null, double? topRightLng = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "bottomLeftLat", bottomLeftLat); AddParameter(p, "bottomLeftLng", bottomLeftLng); AddParameter(p, "topRightLat", topRightLat); AddParameter(p, "topRightLng", topRightLng); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<LocationMinModelGeoListResponse>("locations/boundingbox-minimal", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationPoiResultListResponse> Locations_GetBoundingBoxTileAsync(int? x = null, int? y = null, int? zoomLevel = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, int? overlapPixel = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "x", x); AddParameter(p, "y", y); AddParameter(p, "zoomLevel", zoomLevel); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "overlapPixel", overlapPixel); return await SendGetAsync<LocationPoiResultListResponse>("locations/boundingbox-tile", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationModel> Locations_GetByIdAsync(string id, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, string? paymentMethodId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_evseUid", filter_evseUid); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "paymentMethodId", paymentMethodId); return await SendGetAsync<LocationModel>($"locations/{Uri.EscapeDataString(id)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationModel> Locations_GetByEvseAsync(string evseUid, string? filter_appToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_appToken", filter_appToken); return await SendGetAsync<LocationModel>($"locations/evse/{Uri.EscapeDataString(evseUid)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationSummaryGeoListResponse> Locations_GetAllAsync(string? filter_appToken = null, string? filter_country = null, IEnumerable<string>? filter_locationIds = null, DateTimeOffset? filter_lastUpdated = null, bool? filter_restrictedAccess = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_country", filter_country); AddEnumerableParameter(p, "filter_locationIds", filter_locationIds); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<LocationSummaryGeoListResponse>("locations", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationAvailabilityResponse> Locations_GetAvailabilityAsync(LocationAvailabilityRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<LocationAvailabilityResponse>("locations/availability", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<LocationModelGeoListResponse> LocationsV2_SearchAsync(string? q = null, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, string? paymentMethodId = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "q", q); AddParameter(p, "filter_evseUid", filter_evseUid); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); AddParameter(p, "paymentMethodId", paymentMethodId); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<LocationModelGeoListResponse>("v2.1/locations/search", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationModelGeoListResponse> LocationsV2_GetNearbyAsync(double? latitude = null, double? longitude = null, string? paymentMethodId = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, int? pageSize = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "latitude", latitude); AddParameter(p, "longitude", longitude); AddParameter(p, "paymentMethodId", paymentMethodId); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "pageSize", pageSize); return await SendGetAsync<LocationModelGeoListResponse>("v2.1/locations/nearby", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationModelGeoListResponse> LocationsV2_GetBoundingBoxAsync(double? bottomLeftLat = null, double? bottomLeftLng = null, double? topRightLat = null, double? topRightLng = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, string? paymentMethodId = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "bottomLeftLat", bottomLeftLat); AddParameter(p, "bottomLeftLng", bottomLeftLng); AddParameter(p, "topRightLat", topRightLat); AddParameter(p, "topRightLng", topRightLng); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); AddParameter(p, "paymentMethodId", paymentMethodId); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<LocationModelGeoListResponse>("v2.1/locations/boundingbox", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationMinModelGeoListResponse> LocationsV2_GetBoundingBoxMinimalAsync(double? bottomLeftLat = null, double? bottomLeftLng = null, double? topRightLat = null, double? topRightLng = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, double? userLatitude = null, double? userLongitude = null, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "bottomLeftLat", bottomLeftLat); AddParameter(p, "bottomLeftLng", bottomLeftLng); AddParameter(p, "topRightLat", topRightLat); AddParameter(p, "topRightLng", topRightLng); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); AddParameter(p, "userLatitude", userLatitude); AddParameter(p, "userLongitude", userLongitude); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<LocationMinModelGeoListResponse>("v2.1/locations/boundingbox-minimal", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationModel> LocationsV2_GetByIdAsync(string id, string? paymentMethodId = null, string? filter_evseUid = null, string? filter_appToken = null, bool? filter_isAvailable = null, bool? filter_isFavorite = null, bool? filter_directPayEnabled = null, ChargeAssistPowerType? filter_powerType = null, ChargeAssistConnectorType? filter_connectorType = null, IEnumerable<ChargeAssistConnectorType>? filter_connectorTypes = null, int? filter_minKw = null, int? filter_maxKw = null, bool? filter_restrictedAccess = null, string? filter_country = null, string? filter_customerExternalId = null, DateTimeOffset? filter_lastUpdated = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "paymentMethodId", paymentMethodId); AddParameter(p, "filter_evseUid", filter_evseUid); AddParameter(p, "filter_appToken", filter_appToken); AddParameter(p, "filter_isAvailable", filter_isAvailable); AddParameter(p, "filter_isFavorite", filter_isFavorite); AddParameter(p, "filter_directPayEnabled", filter_directPayEnabled); AddParameter(p, "filter_powerType", filter_powerType); AddParameter(p, "filter_connectorType", filter_connectorType); AddEnumerableParameter(p, "filter_connectorTypes", filter_connectorTypes?.Select(s => ConvertToString(s, CultureInfo.InvariantCulture))); AddParameter(p, "filter_minKw", filter_minKw); AddParameter(p, "filter_maxKw", filter_maxKw); AddParameter(p, "filter_restrictedAccess", filter_restrictedAccess); AddParameter(p, "filter_country", filter_country); AddParameter(p, "filter_customerExternalId", filter_customerExternalId); AddParameter(p, "filter_lastUpdated", filter_lastUpdated); return await SendGetAsync<LocationModel>($"v2.1/locations/{Uri.EscapeDataString(id)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<LocationModel> LocationsV2_GetByEvseAsync(string evseUid, string? filter_appToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "filter_appToken", filter_appToken); return await SendGetAsync<LocationModel>($"v2.1/locations/evse/{Uri.EscapeDataString(evseUid)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<PaymentMethodModelListResponse> Payment_GetWalletAsync(string appToken, string? locationId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "locationId", locationId); return await SendGetAsync<PaymentMethodModelListResponse>($"payment/{Uri.EscapeDataString(appToken)}/wallet", p, cancellationToken).ConfigureAwait(false); }
    public async Task<PaymentMethodModelListResponse?> Payment_TryGetWalletAsync(string appToken, string? locationId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "locationId", locationId); return await TrySendGetAsync<PaymentMethodModelListResponse>($"payment/{Uri.EscapeDataString(appToken)}/wallet", p, cancellationToken).ConfigureAwait(false); }
    public async Task<PaymentMethodModel> Payment_AddExternalMethodAsync(string appToken, PutExternalPaymentMethodRequest? body = null, CancellationToken cancellationToken = default) => await SendPutAsync<PaymentMethodModel>($"payment/{Uri.EscapeDataString(appToken)}/external", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<PaymentMethodModel> Payment_AddChargeCardAsync(string appToken, PutChargeCardRequest? body = null, CancellationToken cancellationToken = default) => await SendPutAsync<PaymentMethodModel>($"payment/{Uri.EscapeDataString(appToken)}/chargecard", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<PaymentMethodModel> Payment_LinkChargeCardAsync(string appToken, LinkChargeCardRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<PaymentMethodModel>($"payment/{Uri.EscapeDataString(appToken)}/chargecard/link", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<PaymentMethodModel> Payment_UnlinkChargeCardAsync(string appToken, UnLinkChargeCardRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<PaymentMethodModel>($"payment/{Uri.EscapeDataString(appToken)}/chargecard/unlink", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<PaymentMethodModel> Payment_AddPspMethodAsync(string appToken, PspSource pspSource, PutPspTokenRequest? body = null, CancellationToken cancellationToken = default) => await SendPutAsync<PaymentMethodModel>($"payment/{Uri.EscapeDataString(appToken)}/psp/{ConvertToString(pspSource, CultureInfo.InvariantCulture)}/paymentmethod", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task Payment_DeleteMethodAsync(string appToken, string id, CancellationToken cancellationToken = default) => await SendDeleteAsync($"payment/{Uri.EscapeDataString(appToken)}/{Uri.EscapeDataString(id)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<LocationModelListResponse> PrivateLocations_GetAsync(string appToken, int? pageSize = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "pageSize", pageSize); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<LocationModelListResponse>($"privatelocations/{Uri.EscapeDataString(appToken)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<QrResponse> Qr_ParseAsync(QrRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<QrResponse>("qr", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task ServiceStatus_GetAsync(CancellationToken cancellationToken = default) => await SendGetAsync("servicestatus", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<StartResponse> Session_StartAsync(string appToken, StartRequest? body = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["appToken"] = appToken }; return await SendPostAsync<StartResponse>("session/start", body, p, cancellationToken).ConfigureAwait(false); }
    public async Task<StatusResponse> Session_StopAsync(string appToken, StopRequest? body = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["appToken"] = appToken }; return await SendPostAsync<StatusResponse>("session/stop", body, p, cancellationToken).ConfigureAwait(false); }
    public async Task Session_UpdateMileageAsync(string appToken, SessionMileageRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync($"session/{Uri.EscapeDataString(appToken)}/mileage", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<StatusResponse> Session_GetStatusAsync(string appToken, string chargeSessionId, int? maxDataPoints = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["appToken"] = appToken, ["chargeSessionId"] = chargeSessionId }; AddParameter(p, "maxDataPoints", maxDataPoints); return await SendGetAsync<StatusResponse>("session/status", p, cancellationToken).ConfigureAwait(false); }
    public async Task<HighPriorityResponse> Session_SetHighPriorityAsync(string? appToken = null, HighPriorityRequest? body = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "appToken", appToken); return await SendPostAsync<HighPriorityResponse>("session/highpriority", body, p, cancellationToken).ConfigureAwait(false); }
    public async Task<ExternalCdrInformationModel> Session_GetExternalCdrAsync(string cdrId, string authId, CancellationToken cancellationToken = default) => await SendGetAsync<ExternalCdrInformationModel>($"session/externalcdr/{Uri.EscapeDataString(cdrId)}/authid/{Uri.EscapeDataString(authId)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<StartResponse> SessionV2_StartAsync(string appToken, StartRequest? body = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["appToken"] = appToken }; return await SendPostAsync<StartResponse>("v2.1/session/start", body, p, cancellationToken).ConfigureAwait(false); }
    public async Task<StatusResponse> SessionV2_StopAsync(string appToken, StopRequest? body = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["appToken"] = appToken }; return await SendPostAsync<StatusResponse>("v2.1/session/stop", body, p, cancellationToken).ConfigureAwait(false); }
    public async Task SessionV2_UpdateMileageAsync(string appToken, SessionMileageRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync($"v2.1/session/{Uri.EscapeDataString(appToken)}/mileage", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<StatusResponse> SessionV2_GetStatusAsync(string appToken, string chargeSessionId, int? maxDataPoints = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?> { ["appToken"] = appToken, ["chargeSessionId"] = chargeSessionId }; AddParameter(p, "maxDataPoints", maxDataPoints); return await SendGetAsync<StatusResponse>("v2.1/session/status", p, cancellationToken).ConfigureAwait(false); }
    public async Task<HighPriorityResponse> SessionV2_SetHighPriorityAsync(string? appToken = null, HighPriorityRequest? body = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "appToken", appToken); return await SendPostAsync<HighPriorityResponse>("v2.1/session/highpriority", body, p, cancellationToken).ConfigureAwait(false); }
    public async Task<IActionResult> SessionFailedPayments_InitiateAsync(RetryFailedSessionPaymentRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<IActionResult>("sessionfailedpayments/initiate", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<FailedSessionPaymentModelListResponse> SessionFailedPayments_GetAsync(string appToken, string? paymentMethodId = null, string? continuationToken = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "paymentMethodId", paymentMethodId); AddParameter(p, "continuationToken", continuationToken); return await SendGetAsync<FailedSessionPaymentModelListResponse>($"sessionfailedpayments/{Uri.EscapeDataString(appToken)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<SessionRatingV2Model> SessionRating_CreateAsync(SessionRatingAllV2Request? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<SessionRatingV2Model>("sessionrating", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<SessionRatingV2Model> SessionRating_SetRatingAsync(SessionRatingV2Request? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<SessionRatingV2Model>("sessionrating/rating", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<SessionRatingV2Model> SessionRating_SetFeedbackAsync(SessionRatingFeedbackV2Request? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<SessionRatingV2Model>("sessionrating/feedback", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<SessionRatingV2Model> SessionRating_GetAsync(string chargeSessionId, CancellationToken cancellationToken = default) => await SendGetAsync<SessionRatingV2Model>($"sessionrating/{Uri.EscapeDataString(chargeSessionId)}", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<ICollection<RatingOptionV2Model>> SessionRating_GetOptionsAsync(CancellationToken cancellationToken = default) => await SendGetAsync<ICollection<RatingOptionV2Model>>("sessionrating/ratingoptions", cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<WalletTariffItemListResponse> Tariff_GetAsync(string appToken, string locationId, string evseUid, string? connectorId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "connectorId", connectorId); return await SendGetAsync<WalletTariffItemListResponse>($"tariff/{Uri.EscapeDataString(appToken)}/evse/{Uri.EscapeDataString(locationId)}/{Uri.EscapeDataString(evseUid)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<WalletTariffItem> Tariff_GetDefaultAsync(string locationId, string evseUid, string? connectorId = null, CancellationToken cancellationToken = default) { var p = new Dictionary<string, string?>(); AddParameter(p, "connectorId", connectorId); return await SendGetAsync<WalletTariffItem>($"tariff/evse/{Uri.EscapeDataString(locationId)}/{Uri.EscapeDataString(evseUid)}", p, cancellationToken).ConfigureAwait(false); }
    public async Task<BulkTariffResponse> Tariff_GetBulkAsync(string appToken, string paymentMethodId, BulkTariffsRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<BulkTariffResponse>($"bulktariff/{Uri.EscapeDataString(appToken)}/paymentmethod/{Uri.EscapeDataString(paymentMethodId)}", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<VidMappingModel> Vid_RegisterAsync(string appToken, VidMappingRegisterRequestExternal? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<VidMappingModel>($"vid/{Uri.EscapeDataString(appToken)}/register", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<VidMappingModel> Vid_DeregisterAsync(string appToken, CancellationToken cancellationToken = default) => await SendPostAsync<VidMappingModel>($"vid/{Uri.EscapeDataString(appToken)}/deregister", null, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task<VidMappingModel> Vid_ChangePaymentMethodAsync(string appToken, VidChangePaymentMethodRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync<VidMappingModel>($"vid/{Uri.EscapeDataString(appToken)}/changepaymentmethod", body, cancellationToken: cancellationToken).ConfigureAwait(false);
    public async Task Webhooks_ReceivePaymentStatusAsync(PaymentStatusRequest? body = null, CancellationToken cancellationToken = default) => await SendPostAsync("webhooks/paymentstatus", body, cancellationToken: cancellationToken).ConfigureAwait(false);

    protected override Exception CreateApiException(
        string message, int statusCode, string? response,
        IReadOnlyDictionary<string, IEnumerable<string>> headers, Exception? innerException)
        => new ChargeAssistApiException(message, statusCode, response, headers, innerException);
}

